[package]
name = "bs3vsdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bs3 = { path = "../bs3", version = "0.1" }

# For vsdb and sha3
vsdb = "0.14"
