[package]
name = "bs3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# bs3 = { git = "https://github.com/tiannian/bs3.git" }
digest = "0.10.2"

