[package]
name = "baseline-rt-memory"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
baseline = { path = "../baseline" }
baseline-runtime = { path = "../runtime" }
